server:
  port: 8020

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/docker_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: hodo0927
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
